import {transferHandler} from './handler.ts';
function assert(value:unknown,message='Assertion failed'):void {if(!value)throw Error(message);}
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const item={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',title:'QR test',category:'General',kind:'Protocol',summary:'',steps:[],equipment:[],notes:'kept',photos:[],author:'',reviewer:'',reviewedOn:'',revision:1,updatedAt:'2026-09-27T00:00:00Z',favorite:false,imported:false};
const pkg={format:'VetPilot.MyClinic',schemaVersion:1,exportedAt:'2026-09-27T00:00:00Z',items:[item]};
function fixture(){const rows:Record<string,any>[]=[];let dbCalls=0;
 const fetcher=(async(input:RequestInfo|URL,init?:RequestInit)=>{const u=new URL(String(input));if(u.pathname==='/auth/v1/user'){const auth=new Headers(init?.headers).get('Authorization');if(auth==='Bearer invalid')return Response.json({error:'invalid'},{status:401});return Response.json({id:auth==='Bearer other'?other:owner,is_anonymous:auth==='Bearer anonymous'});}
 dbCalls++;assert(new Headers(init?.headers).get('apikey')==='secret','Service key stays on server');
 if(u.pathname.endsWith('/rpc/create_qr_transfer')){const body=JSON.parse(String(init?.body));const row={id:crypto.randomUUID(),owner_id:body.transfer_owner,collection:body.transfer_collection,token_hash:body.transfer_hash,payload:body.transfer_payload,title:'QR test',item_count:1,expires_at:new Date(Date.now()+86400000).toISOString()};rows.push(row);return Response.json([row]);}
 const matches=(r:Record<string,any>)=>['owner_id','collection','id','token_hash'].every(k=>!u.searchParams.has(k)||u.searchParams.get(k)==='eq.'+r[k])&&(!u.searchParams.has('expires_at')||r.expires_at>u.searchParams.get('expires_at')!.slice(3));
 const selected=rows.filter(matches);if(init?.method==='DELETE'){for(const r of selected)rows.splice(rows.indexOf(r),1);return Response.json([]);}return Response.json(selected);
 }) as typeof fetch;
 const handler=transferHandler({url:'https://test.invalid',key:'public',serviceKey:'secret'},fetcher);
 const call=(action:string,values:Record<string,unknown>={},auth='owner',method='POST')=>handler(new Request('https://test.invalid/function',{method,headers:auth?{'Authorization':'Bearer '+auth,'Content-Type':'application/json'}:{'Content-Type':'application/json'},body:method==='POST'?JSON.stringify({owner:auth==='other'?other:owner,collection:'clinic',action,...values}):undefined}));
 return {rows,call,calls:()=>dbCalls};
}
Deno.test('unauthenticated, anonymous and mismatched accounts never reach transfer data',async()=>{const f=fixture();for(const auth of ['', 'invalid','anonymous'])assert((await f.call('list',{},auth)).status===401);assert((await f.call('list',{owner:other})).status===409);assert(f.calls()===0);});
Deno.test('share is a selected snapshot, opaque token is hashed, list hides payload and token',async()=>{const f=fixture();const r=await f.call('create',{package:pkg});assert(r.status===200);const shared=await r.json();assert(/^https:\/\/vetpilotapp.org\/transfer#v1:clinic:[\w-]{43}$/.test(shared.url));const token=shared.url.split(':').at(-1);assert(f.rows[0].token_hash.length===64&&f.rows[0].token_hash!==token);const list=await(await f.call('list')).json();assert(list.transfers.length===1&&!JSON.stringify(list).includes('token_hash')&&!JSON.stringify(list).includes('payload'));assert((await(await f.call('list',{},'other')).json()).transfers.length===0);});
Deno.test('recipient with token can receive, cannot revoke owner link; owner revocation prevents later access',async()=>{const f=fixture();const s=await(await f.call('create',{package:pkg})).json();const token=s.url.split(':').at(-1);let r=await f.call('resolve',{token},'other');assert(r.status===200);assert((await r.json()).package.items[0].notes==='kept');await f.call('revoke',{id:s.id},'other');assert(f.rows.length===1);await f.call('revoke',{id:s.id});assert(f.rows.length===0);assert((await f.call('resolve',{token},'other')).status===404);});
Deno.test('expired, wrong-token and wrong-collection links cannot resolve',async()=>{const f=fixture();const s=await(await f.call('create',{package:pkg})).json(),token=s.url.split(':').at(-1);assert((await f.call('resolve',{token:'z'.repeat(43)})).status===404);assert((await f.call('resolve',{token,collection:'cytology'})).status===404);f.rows[0].expires_at='2000-01-01T00:00:00Z';assert((await f.call('resolve',{token})).status===404);});
Deno.test('malformed packages and unrelated sections are rejected before database access',async()=>{const f=fixture();for(const values of [{package:{...pkg,items:[]}},{collection:'dose',package:pkg},{package:{...pkg,schemaVersion:2}},{package:{...pkg,items:[item,item]}}])assert((await f.call('create',values)).status===400);assert(f.calls()===0);});
