import Foundation

enum LabProvider: String, CaseIterable, Identifiable {
    case idexx = "IDEXX"
    case msu = "MSU"
    var id: String { rawValue }
    var title: String { self == .idexx ? "IDEXX Reference Laboratories" : "Michigan State VDL" }
}
struct LabTestEntry: Identifiable {
    let id, provider, code, name, purpose, species, specimen, amount, tube, preparation, handling, notes, source: String
    let available: Bool
}
enum LabworkCatalog {
    static let reviewed = "2026-09-23"
    static let idexxGuide = "https://www.idexx.com/files/06-0013212-06-irl-specimen-guide-en-us.pdf"
    static let tubeNote = "Match the additive and container, not cap color alone. Colors vary by manufacturer. Volumes are submission specimens, not a calculated blood-draw volume."
    static func preparation(_ key: String) -> String {
        switch key {
        case "idexxSerum", "idexxMulti":
            return "Serum: allow a distinct clot (about 20–30 minutes for red-top collection), then centrifuge and transfer to a plain tube. Confirm spin force/time against the specific tube and centrifuge instructions; the IDEXX guide uses differing units/settings across its tables. Keep EDTA blood separate and unspun."
        case "idexxBlood": return "Mix EDTA blood promptly by gentle inversion; do not allow clotting."
        case "idexxSlides": return "Spread and air-dry slides; do not fix, coverslip or expose to oil."
        case "idexxFluid": return "Make slides promptly. Keep a separate EDTA fluid aliquot; verify test-specific minimum volume before collection."
        case "msuSerum": return "Clot at room temperature for 30–60 minutes. Centrifuge and pipette serum into a plain leakproof tube; do not ship whole blood or a serum separator tube. MSU does not specify a spin speed/time on these entries: use the validated tube/centrifuge procedure. Cap color is not specified by MSU; verify the serum tube additive."
        case "msuACTH": return "Do not clot. For dogs/cats, centrifuge immediately; transfer EDTA plasma to plain leakproof plastic, label EDTA plasma, and freeze."
        case "msuCBC": return "Gently mix EDTA whole blood. Make two direct, air-dried, unstained and unfixed smears. Do not spin."
        case "msuSlides": return "Prepare unstained, unfixed slides; identify patient and tissue site."
        default: return "Confirm current availability with the laboratory before collection."
        }
    }
    static func search(_ query: String, provider: LabProvider? = nil) -> [LabTestEntry] {
        let tokens = query.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: Locale(identifier: "en_US_POSIX")).split(whereSeparator: { $0.isWhitespace })
        return tests.filter { item in
            guard provider == nil || item.provider == provider?.rawValue else { return false }
            let text = [item.name,item.code,item.provider,item.purpose,item.species,item.specimen,item.tube,item.notes,preparation(item.preparation), item.provider == "MSU" ? "Michigan State" : "IDEXX"].joined(separator: " ").folding(options: [.caseInsensitive,.diacriticInsensitive], locale: Locale(identifier: "en_US_POSIX"))
            return tokens.allSatisfy { text.contains($0) }
        }.sorted { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
    }
    static let tests: [LabTestEntry] = [
        .init(id: "IDEXX-375", provider: "IDEXX", code: "375", name: "IDEXX CBC", purpose: "Blood-cell counts for routine screening.", species: "Dog / Cat", specimen: "EDTA whole blood", amount: "1 mL", tube: "Lavender • EDTA", preparation: "idexxBlood", handling: "Refrigerate; do not freeze or spin whole blood.", notes: "Use a correctly filled collection tube.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/cbc-options/", available: true),
        .init(id: "IDEXX-300", provider: "IDEXX", code: "300", name: "IDEXX CBC-Select", purpose: "Blood-cell counts plus microscopic blood-film review for sick patients.", species: "Dog / Cat", specimen: "EDTA whole blood", amount: "1 mL", tube: "Lavender • EDTA", preparation: "idexxBlood", handling: "Refrigerate; do not freeze or spin whole blood.", notes: "Use a correctly filled collection tube.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/cbc-options/", available: true),
        .init(id: "IDEXX-1849", provider: "IDEXX", code: "1849", name: "Spec cPL", purpose: "Pancreatic lipase assessment supporting pancreatitis evaluation.", species: "Dog", specimen: "Serum", amount: "1 mL", tube: "Red • serum collection → plain white transfer tube", preparation: "idexxSerum", handling: "Refrigerate separated serum.", notes: "Fasting specimen preferred; assess fasting suitability.", source: "https://www.idexx.com/files/spec_cpl-spec_fpl_dxu_h.pdf", available: true),
        .init(id: "IDEXX-2493", provider: "IDEXX", code: "2493", name: "Spec fPL", purpose: "Pancreatic lipase assessment supporting pancreatitis evaluation.", species: "Cat", specimen: "Serum", amount: "1 mL", tube: "Red • serum collection → plain white transfer tube", preparation: "idexxSerum", handling: "Refrigerate separated serum.", notes: "Fasting specimen preferred; assess fasting suitability.", source: "https://www.idexx.com/files/spec_cpl-spec_fpl_dxu_h.pdf", available: true),
        .init(id: "IDEXX-2500", provider: "IDEXX", code: "2500", name: "Senior Screen with Spec cPL", purpose: "Chemistry, CBC, pancreatic lipase and thyroid assessment; senior screens include urine.", species: "Dog", specimen: "Multiple specimens", amount: "2 mL serum + 1 mL EDTA blood + 5 mL urine", tube: "Red → white serum; lavender EDTA; sterile urine container where listed", preparation: "idexxMulti", handling: "Refrigerate; keep whole blood unfrozen.", notes: "Dog panels: overnight fasting; cat panels: fasting preferred. Clinician decides suitability.", source: "https://www.idexx.com/files/spec_cpl-spec_fpl_dxu_h.pdf", available: true),
        .init(id: "IDEXX-2743", provider: "IDEXX", code: "2743", name: "Senior Screen with Spec fPL", purpose: "Chemistry, CBC, pancreatic lipase and thyroid assessment; senior screens include urine.", species: "Cat", specimen: "Multiple specimens", amount: "2 mL serum + 1 mL EDTA blood + 5 mL urine", tube: "Red → white serum; lavender EDTA; sterile urine container where listed", preparation: "idexxMulti", handling: "Refrigerate; keep whole blood unfrozen.", notes: "Dog panels: overnight fasting; cat panels: fasting preferred. Clinician decides suitability.", source: "https://www.idexx.com/files/spec_cpl-spec_fpl_dxu_h.pdf", available: true),
        .init(id: "IDEXX-2377", provider: "IDEXX", code: "2377", name: "Total Health Plus with Spec cPL", purpose: "Chemistry, CBC, pancreatic lipase and thyroid assessment; senior screens include urine.", species: "Dog", specimen: "Multiple specimens", amount: "2 mL serum + 1 mL EDTA blood", tube: "Red → white serum; lavender EDTA; sterile urine container where listed", preparation: "idexxMulti", handling: "Refrigerate; keep whole blood unfrozen.", notes: "Dog panels: overnight fasting; cat panels: fasting preferred. Clinician decides suitability.", source: "https://www.idexx.com/files/spec_cpl-spec_fpl_dxu_h.pdf", available: true),
        .init(id: "IDEXX-2732", provider: "IDEXX", code: "2732", name: "ADRChek Plus with Spec fPL", purpose: "Chemistry, CBC, pancreatic lipase and thyroid assessment; senior screens include urine.", species: "Cat", specimen: "Multiple specimens", amount: "2 mL serum + 1 mL EDTA blood", tube: "Red → white serum; lavender EDTA; sterile urine container where listed", preparation: "idexxMulti", handling: "Refrigerate; keep whole blood unfrozen.", notes: "Dog panels: overnight fasting; cat panels: fasting preferred. Clinician decides suitability.", source: "https://www.idexx.com/files/spec_cpl-spec_fpl_dxu_h.pdf", available: true),
        .init(id: "IDEXX-8988", provider: "IDEXX", code: "8988", name: "FGF-23 — Feline", purpose: "Evaluates phosphorus regulation in feline chronic kidney disease.", species: "Cat", specimen: "Serum", amount: "1 mL", tube: "Red → plain white transfer tube", preparation: "idexxSerum", handling: "Refrigeration preferred; freezing unnecessary.", notes: "Domestic feline serum only.", source: "https://www.idexx.com/files/fgf-23-diagnostic-update.pdf", available: true),
        .init(id: "IDEXX-8990", provider: "IDEXX", code: "8990", name: "Renal Monitoring with FGF-23 + CBC-Select", purpose: "Feline renal panel, CBC and FGF-23.", species: "Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA blood", tube: "Red → white serum; lavender EDTA", preparation: "idexxMulti", handling: "Refrigerate; do not freeze whole blood.", notes: "Code 8990 includes CBC-Select; verify requested panel.", source: "https://www.idexx.com/files/fgf-23-diagnostic-update.pdf", available: true),
        .init(id: "IDEXX-605", provider: "IDEXX", code: "605", name: "Priority Cytology — one site", purpose: "Microscopic assessment of a mass or lesion.", species: "Dog / Cat", specimen: "Prepared slides", amount: "Up to 4 slides per site", tube: "Rigid slide carrier • no blood vial", preparation: "idexxSlides", handling: "Room temperature; protect from formalin fumes.", notes: "Label patient and collection site. Unstained slides preferred.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "IDEXX-2801", provider: "IDEXX", code: "2801", name: "Standard Cytology — one site", purpose: "Microscopic assessment of a mass or lesion.", species: "Dog / Cat", specimen: "Prepared slides", amount: "Up to 4 slides per site", tube: "Rigid slide carrier • no blood vial", preparation: "idexxSlides", handling: "Room temperature; protect from formalin fumes.", notes: "Label patient and collection site. Unstained slides preferred.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "IDEXX-606", provider: "IDEXX", code: "606", name: "Lymph Node Cytology — Standard", purpose: "Microscopic assessment of lymph nodes.", species: "Dog / Cat", specimen: "Prepared slides", amount: "Up to 10 slides", tube: "Rigid slide carrier • no blood vial", preparation: "idexxSlides", handling: "Room temperature; protect from formalin fumes.", notes: "Label each node/site; verify service code.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "IDEXX-609", provider: "IDEXX", code: "609", name: "Lymph Node Cytology — Priority", purpose: "Microscopic assessment of lymph nodes.", species: "Dog / Cat", specimen: "Prepared slides", amount: "Up to 10 slides", tube: "Rigid slide carrier • no blood vial", preparation: "idexxSlides", handling: "Room temperature; protect from formalin fumes.", notes: "Label each node/site; verify service code.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "IDEXX-9057", provider: "IDEXX", code: "9057", name: "Body Cavity Fluid Analysis — one site", purpose: "Cell counts and cytology of an effusion.", species: "Dog / Cat", specimen: "Fluid + slides", amount: "1–4 slides; fluid minimum: confirm in current directory", tube: "Lavender • EDTA fluid; rigid slide carrier", preparation: "idexxFluid", handling: "Keep slides dry at room temperature; confirm fluid transport in directory.", notes: "Do not use serum gel or clot-activator tubes. A plain sterile aliquot is separate if culture is requested.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "MSU-20010", provider: "MSU", code: "20010", name: "Canine Thyroid Diagnostic Profile", purpose: "Thyroid hormones and antibodies for canine thyroid evaluation.", species: "Dog", specimen: "Serum", amount: "2 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate or freeze; prevent warming in transit.", notes: "Avoid hemolysis/lipemia; medications affect interpretation.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1388", available: true),
        .init(id: "MSU-20011", provider: "MSU", code: "20011", name: "Premium Canine Thyroid Profile", purpose: "Thyroid assessment including free T4 by equilibrium dialysis.", species: "Dog", specimen: "Serum", amount: "2 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "Warm exposure can falsely increase free T4 by dialysis.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1427", available: true),
        .init(id: "MSU-20016_", provider: "MSU", code: "20016_", name: "Feline Thyroid Profile — Premium", purpose: "TT4, TT3 and free T4 by equilibrium dialysis.", species: "Cat", specimen: "Serum", amount: "2 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "Avoid hemolysis and lipemia.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=2171", available: true),
        .init(id: "MSU-20017", provider: "MSU", code: "20017", name: "Cortisol — Baseline", purpose: "Baseline adrenal-function assessment; not a stand-alone Cushing’s diagnosis.", species: "Dog / Cat", specimen: "Serum", amount: "0.5 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "Serum only; label baseline versus post-stimulation samples.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1637", available: true),
        .init(id: "MSU-20031", provider: "MSU", code: "20031", name: "Insulin Autoantibody", purpose: "Investigates insulin antibodies in poorly controlled diabetes.", species: "Dog / Cat", specimen: "Serum", amount: "0.5 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1494", available: true),
        .init(id: "MSU-20005", provider: "MSU", code: "20005", name: "Insulin-like Growth Factor-1 (IGF-1)", purpose: "Supports investigation of growth-hormone excess or deficiency.", species: "Dog / Cat", specimen: "Serum", amount: "0.75 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "Serum pathway shown. Plasma is an alternative; verify its collection instructions with MSU.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1401", available: true),
        .init(id: "MSU-20033", provider: "MSU", code: "20033", name: "Parathyroid Hormone + Ionized Calcium", purpose: "Evaluates calcium regulation and parathyroid function.", species: "Dog / Cat", specimen: "Serum", amount: "1 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Freeze; ship on ice overnight to arrive frozen or chilled.", notes: "Avoid separator gel: it can falsely increase calcium. Heparinized plasma is an alternative; never EDTA/citrate for this test.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1496", available: true),
        .init(id: "MSU-20006", provider: "MSU", code: "20006", name: "Endogenous ACTH", purpose: "Helps differentiate adrenal disease after appropriate diagnostic workup.", species: "Dog / Cat", specimen: "EDTA plasma", amount: "1 mL", tube: "Lavender • EDTA collection → plain leakproof PLASTIC transfer tube", preparation: "msuACTH", handling: "Freeze immediately after separation; overnight shipment on ice, arriving frozen/chilled.", notes: "Use plastic: ACTH binds glass. Collect before corticosteroids when clinically appropriate. This is the dog/cat protocol.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1706", available: true),
        .init(id: "MSU-11600", provider: "MSU", code: "11600", name: "CBC with Differential", purpose: "Blood-cell counts, reticulocytes and smear review.", species: "Dog / Cat", specimen: "EDTA whole blood + slides", amount: "0.25 mL minimum + 2 direct smears", tube: "Lavender • EDTA; rigid slide carrier", preparation: "msuCBC", handling: "Whole blood on cold pack; slides in rigid holder outside chilled compartment.", notes: "Tube must also be at least half full. Do not centrifuge or freeze.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1760", available: true),
        .init(id: "MSU-11294", provider: "MSU", code: "11294", name: "Cytology — Slides Only", purpose: "Microscopic evaluation of aspirated tissue.", species: "Dog / Cat", specimen: "Unstained slides", amount: "Slide count not specified; confirm for submission", tube: "Rigid slide carrier • no blood vial", preparation: "msuSlides", handling: "Rigid slide carrier; no formalin or cold packs.", notes: "Unstained, unfixed slides; label each site and include history.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1777", available: true),
        .init(id: "MSU-20014", provider: "MSU", code: "20014", name: "OFA Canine Thyroid Profile", purpose: "Thyroid testing for OFA registry submission.", species: "Dog", specimen: "Serum", amount: "2 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Freeze before overnight shipment on ice; follow current OFA acceptance criteria.", notes: "Fasting required. No thyroid therapy in prior 3 months under OFA criteria; do not stop prescribed treatment without the veterinarian. Include current OFA form.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1629", available: true),
        .init(id: "MSU-20004", provider: "MSU", code: "20004", name: "PTHrP", purpose: "Calcium-related malignancy investigation.", species: "Dog / Cat", specimen: "Unavailable", amount: "Do not collect for this unavailable test", tube: "No collection instruction while unavailable", preparation: "unavailable", handling: "Do not ship for this test.", notes: "MSU lists this test as unavailable. Review the PTH + ionized calcium option (20033) with the veterinarian.", source: "https://cvm.msu.edu/vdl/news/2026/extended-unavailability-of-pthrp-and-malignancy-profile", available: false),
        .init(id: "MSU-20030", provider: "MSU", code: "20030", name: "Malignancy Profile", purpose: "Calcium-related malignancy investigation.", species: "Dog / Cat", specimen: "Unavailable", amount: "Do not collect for this unavailable test", tube: "No collection instruction while unavailable", preparation: "unavailable", handling: "Do not ship for this test.", notes: "MSU lists this test as unavailable. Review the PTH + ionized calcium option (20033) with the veterinarian.", source: "https://cvm.msu.edu/vdl/news/2026/extended-unavailability-of-pthrp-and-malignancy-profile", available: false)
    ]
}
