import Foundation

enum LabProvider: String, CaseIterable, Identifiable {
    case idexx = "IDEXX"
    case msu = "MSU"
    var id: String { rawValue }
    var title: String { self == .idexx ? "IDEXX Reference Laboratories" : "Michigan State VDL" }
}
struct LabTestEntry: Identifiable {
    let id, provider, code, name, purpose, species, specimen, amount, tube, preparation, handling, notes, source: String
    let available: Bool
    var components: String = ""
}
enum LabworkCatalog {
    static let reviewed = "2026-09-23"
    static let idexxGuide = "https://www.idexx.com/files/06-0013212-06-irl-specimen-guide-en-us.pdf"
    static let tubeNote = "Match the additive and container, not cap color alone. Colors vary by manufacturer. Volumes are submission specimens, not a calculated blood-draw volume."
    static func preparation(_ key: String) -> String {
        switch key {
        case "idexxSerum", "idexxMulti":
            return "Serum: allow a distinct clot (about 20–30 minutes for red-top collection), then centrifuge and transfer to a plain tube. Confirm spin force/time against the specific tube and centrifuge instructions; the IDEXX guide uses differing units/settings across its tables. Keep EDTA blood separate and unspun."
        case "idexxCardiopetDog":
            return "Do not clot. Collect into a correctly filled lavender EDTA tube and gently invert 8–10 times. Centrifuge promptly using the validated tube/centrifuge procedure. Transfer the separated plasma to a plain, additive-free plastic tube (commonly white top) and label EDTA plasma. Submit 1 mL separated plasma; do not submit whole blood for this test."
        case "idexxCardiopetCat":
            return "Choose one specimen pathway. Serum: allow a complete clot (about 20–30 minutes in red-top collection), then centrifuge and transfer serum to a plain plastic tube. EDTA plasma: gently mix a correctly filled lavender tube, allow no clotting, then centrifuge and separate plasma into a plain plastic tube. Use validated tube/centrifuge settings. Label the specimen serum or EDTA plasma; submit 1 mL of the chosen separated specimen, not whole blood."
        case "idexxBlood": return "Mix EDTA blood promptly by gentle inversion; do not allow clotting."
        case "idexxSlides": return "Spread and air-dry slides; do not fix, coverslip or expose to oil."
        case "idexxFluid": return "Make slides promptly. Keep a separate EDTA fluid aliquot; verify test-specific minimum volume before collection."
        case "msuSerum": return "Clot at room temperature for 30–60 minutes. Centrifuge and pipette serum into a plain leakproof tube; do not ship whole blood or a serum separator tube. MSU does not specify a spin speed/time on these entries: use the validated tube/centrifuge procedure. Cap color is not specified by MSU; verify the serum tube additive."
        case "msuACTH": return "Do not clot. For dogs/cats, centrifuge immediately; transfer EDTA plasma to plain leakproof plastic, label EDTA plasma, and freeze."
        case "msuCBC": return "Gently mix EDTA whole blood. Make two direct, air-dried, unstained and unfixed smears. Do not spin."
        case "msuSlides": return "Prepare unstained, unfixed slides; identify patient and tissue site."
        default: return "Confirm current availability with the laboratory before collection."
        }
    }
    static func search(_ query: String, provider: LabProvider? = nil) -> [LabTestEntry] {
        let tokens = query.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: Locale(identifier: "en_US_POSIX")).split(whereSeparator: { $0.isWhitespace })
        return tests.filter { item in
            guard provider == nil || item.provider == provider?.rawValue else { return false }
            let text = [item.name,item.code,item.provider,item.purpose,item.species,item.specimen,item.tube,item.notes,item.components,preparation(item.preparation), item.provider == "MSU" ? "Michigan State" : "IDEXX"].joined(separator: " ").folding(options: [.caseInsensitive,.diacriticInsensitive], locale: Locale(identifier: "en_US_POSIX"))
            return tokens.allSatisfy { text.contains($0) }
        }.sorted { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
    }
    static let tests: [LabTestEntry] = [
        .init(id: "IDEXX-28079999", provider: "IDEXX", code: "28079999", name: "Young Wellness", purpose: "Basic wellness assessment using chemistry markers and blood-cell counts.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA whole blood", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 10 with IDEXX SDMA Test, IDEXX CBC"),
        .init(id: "IDEXX-2807", provider: "IDEXX", code: "2807", name: "Young Wellness Select", purpose: "Basic wellness assessment using chemistry markers and blood-cell counts.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA whole blood", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 10 with IDEXX SDMA Test, IDEXX CBC-Select"),
        .init(id: "IDEXX-10139999", provider: "IDEXX", code: "10139999", name: "Total Health Profile", purpose: "Broad send-out chemistry and blood-cell assessment for general health evaluation.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA whole blood", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. Full send-out bloodwork with comprehensive chemistry and CBC. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, IDEXX CBC"),
        .init(id: "IDEXX-1013", provider: "IDEXX", code: "1013", name: "Total Health Profile Select", purpose: "Broad send-out chemistry and blood-cell assessment for general health evaluation.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA whole blood", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. Full send-out bloodwork with comprehensive chemistry and CBC. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, IDEXX CBC-Select"),
        .init(id: "IDEXX-759999", provider: "IDEXX", code: "759999", name: "Total Health Plus Profile", purpose: "Broad send-out chemistry and blood-cell assessment with thyroid screening.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA whole blood", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. Full send-out bloodwork with comprehensive chemistry and CBC. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, IDEXX CBC, total T4"),
        .init(id: "IDEXX-75", provider: "IDEXX", code: "75", name: "Total Health Plus Profile Select", purpose: "Broad send-out chemistry and blood-cell assessment with thyroid screening.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA whole blood", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. Full send-out bloodwork with comprehensive chemistry and CBC. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, IDEXX CBC-Select, total T4"),
        .init(id: "IDEXX-7809999", provider: "IDEXX", code: "7809999", name: "Senior Profile", purpose: "Senior health assessment of organ function, blood cells, thyroid and urine markers.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood + urine", amount: "2 mL serum + 1 mL EDTA whole blood + 5 mL urine", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood; sterile no-additive urine container", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Refrigerate urine at 2–8°C. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. Collect urine into a sterile, leakproof, additive-free container and record the collection method. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, IDEXX CBC, IDEXX Cystatin B Test (canine/feline only), total T4, urinalysis"),
        .init(id: "IDEXX-780", provider: "IDEXX", code: "780", name: "Senior Profile Select", purpose: "Senior health assessment of organ function, blood cells, thyroid and urine markers.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood + urine", amount: "2 mL serum + 1 mL EDTA whole blood + 5 mL urine", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood; sterile no-additive urine container", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Refrigerate urine at 2–8°C. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. Collect urine into a sterile, leakproof, additive-free container and record the collection method. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, IDEXX CBC-Select, IDEXX Cystatin B Test (canine/feline only), total T4, urinalysis"),
        .init(id: "IDEXX-21769999", provider: "IDEXX", code: "21769999", name: "Geriatric Profile", purpose: "Expanded geriatric assessment of organ function, blood cells, thyroid hormones and urine markers.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood + urine", amount: "2 mL serum + 1 mL EDTA whole blood + 5 mL urine", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood; sterile no-additive urine container", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Refrigerate urine at 2–8°C. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. Collect urine into a sterile, leakproof, additive-free container and record the collection method. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, IDEXX CBC, IDEXX Cystatin B Test, free T4, total T4, urinalysis"),
        .init(id: "IDEXX-2176", provider: "IDEXX", code: "2176", name: "Geriatric Profile Select", purpose: "Expanded geriatric assessment of organ function, blood cells, thyroid hormones and urine markers.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood + urine", amount: "2 mL serum + 1 mL EDTA whole blood + 5 mL urine", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood; sterile no-additive urine container", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Refrigerate urine at 2–8°C. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. Collect urine into a sterile, leakproof, additive-free container and record the collection method. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, IDEXX CBC-Select, IDEXX Cystatin B Test, free T4, total T4, urinalysis"),
        .init(id: "IDEXX-8659999", provider: "IDEXX", code: "8659999", name: "Senior Screen", purpose: "Senior health assessment of organ function, blood cells, thyroid and urine markers.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood + urine", amount: "2 mL serum + 1 mL EDTA whole blood + 5 mL urine", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood; sterile no-additive urine container", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Refrigerate urine at 2–8°C. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. Collect urine into a sterile, leakproof, additive-free container and record the collection method. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 25 with IDEXX SDMA Test, IDEXX CBC, IDEXX Cystatin B Test (canine/feline only), total T4, urinalysis"),
        .init(id: "IDEXX-865", provider: "IDEXX", code: "865", name: "Senior Screen Select", purpose: "Senior health assessment of organ function, blood cells, thyroid and urine markers.", species: "Dog / Cat", specimen: "Serum + EDTA whole blood + urine", amount: "2 mL serum + 1 mL EDTA whole blood + 5 mL urine", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood; sterile no-additive urine container", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Refrigerate urine at 2–8°C. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. No universal fasting duration is specified on this panel record; follow the clinician’s instructions and requirements of any added tests. Collect urine into a sterile, leakproof, additive-free container and record the collection method. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 25 with IDEXX SDMA Test, IDEXX CBC-Select, IDEXX Cystatin B Test (canine/feline only), total T4, urinalysis"),
        .init(id: "IDEXX-2665", provider: "IDEXX", code: "2665", name: "Cardiopet proBNP — Canine", purpose: "Quantitative NT-proBNP, a marker of heart-muscle stretch and stress, to support cardiac health assessment and monitoring. Interpret with examination findings and appropriate imaging.", species: "Dog", specimen: "EDTA plasma", amount: "1 mL separated EDTA plasma", tube: "Lavender EDTA collection → plain additive-free PLASTIC transfer tube (commonly white top)", preparation: "idexxCardiopetDog", handling: "Refrigerate the separated specimen at 2–8°C for up to 7 days; freeze for longer storage. Transport chilled. Avoid repeated freeze–thaw cycles.", notes: "BNP / NT-proBNP send-out test. No special protease-inhibitor tube is required. Avoid gross hemolysis, prolonged glass contact and aged samples. The 1 mL requirement is the final separated specimen, not the blood-draw volume. This is the quantitative reference-laboratory assay; SNAP Feline proBNP is a separate in-clinic test.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/cardiac-health-tests/", available: true, components: "NT-proBNP (quantitative)"),
        .init(id: "IDEXX-2666", provider: "IDEXX", code: "2666", name: "Cardiopet proBNP — Feline", purpose: "Quantitative NT-proBNP, a marker of heart-muscle stretch and stress, to support cardiac health assessment and monitoring. Interpret with examination findings and appropriate imaging.", species: "Cat", specimen: "Serum OR EDTA plasma", amount: "1 mL separated serum OR 1 mL separated EDTA plasma", tube: "Red serum collection OR lavender EDTA collection → plain additive-free PLASTIC transfer tube (commonly white top)", preparation: "idexxCardiopetCat", handling: "Refrigerate the separated specimen at 2–8°C for up to 7 days; freeze for longer storage. Transport chilled.", notes: "BNP / NT-proBNP send-out test. No special protease-inhibitor tube is required. Avoid gross hemolysis, prolonged glass contact and aged samples. The 1 mL requirement is the final separated specimen, not the blood-draw volume. This is the quantitative reference-laboratory assay; SNAP Feline proBNP is a separate in-clinic test.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/cardiac-health-tests/", available: true, components: "NT-proBNP (quantitative)"),
        .init(id: "IDEXX-375", provider: "IDEXX", code: "375", name: "IDEXX CBC", purpose: "Blood-cell counts for routine screening.", species: "Dog / Cat", specimen: "EDTA whole blood", amount: "1 mL", tube: "Lavender • EDTA", preparation: "idexxBlood", handling: "Refrigerate; do not freeze or spin whole blood.", notes: "Use a correctly filled collection tube.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/cbc-options/", available: true),
        .init(id: "IDEXX-300", provider: "IDEXX", code: "300", name: "IDEXX CBC-Select", purpose: "Blood-cell counts plus microscopic blood-film review for sick patients.", species: "Dog / Cat", specimen: "EDTA whole blood", amount: "1 mL", tube: "Lavender • EDTA", preparation: "idexxBlood", handling: "Refrigerate; do not freeze or spin whole blood.", notes: "Use a correctly filled collection tube.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/cbc-options/", available: true),
        .init(id: "IDEXX-1849", provider: "IDEXX", code: "1849", name: "Spec cPL", purpose: "Pancreatic lipase assessment supporting pancreatitis evaluation.", species: "Dog", specimen: "Serum", amount: "1 mL", tube: "Red • serum collection → plain white transfer tube", preparation: "idexxSerum", handling: "Refrigerate separated serum.", notes: "Fasting specimen preferred; assess fasting suitability.", source: "https://www.idexx.com/files/spec_cpl-spec_fpl_dxu_h.pdf", available: true),
        .init(id: "IDEXX-2493", provider: "IDEXX", code: "2493", name: "Spec fPL", purpose: "Pancreatic lipase assessment supporting pancreatitis evaluation.", species: "Cat", specimen: "Serum", amount: "1 mL", tube: "Red • serum collection → plain white transfer tube", preparation: "idexxSerum", handling: "Refrigerate separated serum.", notes: "Fasting specimen preferred; assess fasting suitability.", source: "https://www.idexx.com/files/spec_cpl-spec_fpl_dxu_h.pdf", available: true),
        .init(id: "IDEXX-2500", provider: "IDEXX", code: "2500", name: "Senior Screen with Spec cPL Test Select—Canine", purpose: "Senior health assessment of organ function, blood cells, thyroid and urine markers. Includes the species-specific pancreatic lipase test.", species: "Dog", specimen: "Serum + EDTA whole blood + urine", amount: "2 mL serum + 1 mL EDTA whole blood + 5 mL urine", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood; sterile no-additive urine container", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Refrigerate urine at 2–8°C. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. The directory requests serum after an overnight fast; the veterinarian must determine whether fasting is appropriate. Collect urine into a sterile, leakproof, additive-free container and record the collection method. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 25 with IDEXX SDMA Test, triglycerides, IDEXX CBC-Select, IDEXX Cystatin B Test, Spec cPL Test, total T4, urinalysis"),
        .init(id: "IDEXX-2743", provider: "IDEXX", code: "2743", name: "Senior Screen with Spec fPL Test Select—Feline", purpose: "Senior health assessment of organ function, blood cells, thyroid and urine markers. Includes the species-specific pancreatic lipase test.", species: "Cat", specimen: "Serum + EDTA whole blood + urine", amount: "2 mL serum + 1 mL EDTA whole blood + 5 mL urine", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood; sterile no-additive urine container", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Refrigerate urine at 2–8°C. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. Fasting serum is preferred; the veterinarian determines suitability. Collect urine into a sterile, leakproof, additive-free container and record the collection method. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 25 with IDEXX SDMA Test, IDEXX CBC-Select, IDEXX Cystatin B Test, Spec fPL Test, total T4, urinalysis"),
        .init(id: "IDEXX-2377", provider: "IDEXX", code: "2377", name: "Total Health Plus Profile with Spec cPL Test Select—Canine", purpose: "Broad send-out chemistry and blood-cell assessment with thyroid screening. Includes the species-specific pancreatic lipase test.", species: "Dog", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA whole blood", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. Full send-out bloodwork with comprehensive chemistry and CBC. The directory requests serum after an overnight fast; the veterinarian must determine whether fasting is appropriate. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 27 with IDEXX SDMA Test, triglycerides, IDEXX CBC-Select, Spec cPL Test, total T4"),
        .init(id: "IDEXX-2732", provider: "IDEXX", code: "2732", name: "ADRChek Profile Plus with Spec fPL Test Select—Feline", purpose: "General illness assessment including chemistry, blood cells, pancreatic lipase and thyroid testing. Includes the species-specific pancreatic lipase test.", species: "Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA whole blood", tube: "Red serum collection → plain white transfer tube; lavender EDTA whole blood", preparation: "idexxMulti", handling: "Refrigerate separated serum and EDTA whole blood for prompt submission; keep whole blood unspun and unfrozen. Protect tubes from direct cold-pack contact. Confirm component-specific storage limits in the current order.", notes: "U.S. reference-laboratory send-out panel. Confirm the exact ordered code and any add-ons. Fasting serum is preferred; the veterinarian determines suitability. LTT means lavender-top EDTA whole blood. Fill EDTA tubes to their marked collection volume. Listed serum volume is after separation, not total blood drawn.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/tests-and-services/", available: true, components: "Chem 25 with IDEXX SDMA Test, IDEXX CBC-Select, Spec fPL Test, total T4"),
        .init(id: "IDEXX-8988", provider: "IDEXX", code: "8988", name: "FGF-23 — Feline", purpose: "Evaluates phosphorus regulation in feline chronic kidney disease.", species: "Cat", specimen: "Serum", amount: "1 mL", tube: "Red → plain white transfer tube", preparation: "idexxSerum", handling: "Refrigeration preferred; freezing unnecessary.", notes: "Domestic feline serum only.", source: "https://www.idexx.com/files/fgf-23-diagnostic-update.pdf", available: true),
        .init(id: "IDEXX-8990", provider: "IDEXX", code: "8990", name: "Renal Monitoring with FGF-23 + CBC-Select", purpose: "Feline renal panel, CBC and FGF-23.", species: "Cat", specimen: "Serum + EDTA whole blood", amount: "2 mL serum + 1 mL EDTA blood", tube: "Red → white serum; lavender EDTA", preparation: "idexxMulti", handling: "Refrigerate; do not freeze whole blood.", notes: "Code 8990 includes CBC-Select; verify requested panel.", source: "https://www.idexx.com/files/fgf-23-diagnostic-update.pdf", available: true),
        .init(id: "IDEXX-605", provider: "IDEXX", code: "605", name: "Priority Cytology — one site", purpose: "Microscopic assessment of a mass or lesion.", species: "Dog / Cat", specimen: "Prepared slides", amount: "Up to 4 slides per site", tube: "Rigid slide carrier • no blood vial", preparation: "idexxSlides", handling: "Room temperature; protect from formalin fumes.", notes: "Label patient and collection site. Unstained slides preferred.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "IDEXX-2801", provider: "IDEXX", code: "2801", name: "Standard Cytology — one site", purpose: "Microscopic assessment of a mass or lesion.", species: "Dog / Cat", specimen: "Prepared slides", amount: "Up to 4 slides per site", tube: "Rigid slide carrier • no blood vial", preparation: "idexxSlides", handling: "Room temperature; protect from formalin fumes.", notes: "Label patient and collection site. Unstained slides preferred.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "IDEXX-606", provider: "IDEXX", code: "606", name: "Lymph Node Cytology — Standard", purpose: "Microscopic assessment of lymph nodes.", species: "Dog / Cat", specimen: "Prepared slides", amount: "Up to 10 slides", tube: "Rigid slide carrier • no blood vial", preparation: "idexxSlides", handling: "Room temperature; protect from formalin fumes.", notes: "Label each node/site; verify service code.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "IDEXX-609", provider: "IDEXX", code: "609", name: "Lymph Node Cytology — Priority", purpose: "Microscopic assessment of lymph nodes.", species: "Dog / Cat", specimen: "Prepared slides", amount: "Up to 10 slides", tube: "Rigid slide carrier • no blood vial", preparation: "idexxSlides", handling: "Room temperature; protect from formalin fumes.", notes: "Label each node/site; verify service code.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "IDEXX-9057", provider: "IDEXX", code: "9057", name: "Body Cavity Fluid Analysis — one site", purpose: "Cell counts and cytology of an effusion.", species: "Dog / Cat", specimen: "Fluid + slides", amount: "1–4 slides; fluid minimum: confirm in current directory", tube: "Lavender • EDTA fluid; rigid slide carrier", preparation: "idexxFluid", handling: "Keep slides dry at room temperature; confirm fluid transport in directory.", notes: "Do not use serum gel or clot-activator tubes. A plain sterile aliquot is separate if culture is requested.", source: "https://www.idexx.com/en/veterinary/reference-laboratories/pathology/clinical-pathology/", available: true),
        .init(id: "MSU-20010", provider: "MSU", code: "20010", name: "Canine Thyroid Diagnostic Profile", purpose: "Thyroid hormones and antibodies for canine thyroid evaluation.", species: "Dog", specimen: "Serum", amount: "2 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate or freeze; prevent warming in transit.", notes: "Avoid hemolysis/lipemia; medications affect interpretation.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1388", available: true),
        .init(id: "MSU-20011", provider: "MSU", code: "20011", name: "Premium Canine Thyroid Profile", purpose: "Thyroid assessment including free T4 by equilibrium dialysis.", species: "Dog", specimen: "Serum", amount: "2 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "Warm exposure can falsely increase free T4 by dialysis.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1427", available: true),
        .init(id: "MSU-20016_", provider: "MSU", code: "20016_", name: "Feline Thyroid Profile — Premium", purpose: "TT4, TT3 and free T4 by equilibrium dialysis.", species: "Cat", specimen: "Serum", amount: "2 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "Avoid hemolysis and lipemia.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=2171", available: true),
        .init(id: "MSU-20017", provider: "MSU", code: "20017", name: "Cortisol — Baseline", purpose: "Baseline adrenal-function assessment; not a stand-alone Cushing’s diagnosis.", species: "Dog / Cat", specimen: "Serum", amount: "0.5 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "Serum only; label baseline versus post-stimulation samples.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1637", available: true),
        .init(id: "MSU-20031", provider: "MSU", code: "20031", name: "Insulin Autoantibody", purpose: "Investigates insulin antibodies in poorly controlled diabetes.", species: "Dog / Cat", specimen: "Serum", amount: "0.5 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1494", available: true),
        .init(id: "MSU-20005", provider: "MSU", code: "20005", name: "Insulin-like Growth Factor-1 (IGF-1)", purpose: "Supports investigation of growth-hormone excess or deficiency.", species: "Dog / Cat", specimen: "Serum", amount: "0.75 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Refrigerate at most overnight or freeze; ship on ice overnight/second day.", notes: "Serum pathway shown. Plasma is an alternative; verify its collection instructions with MSU.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1401", available: true),
        .init(id: "MSU-20033", provider: "MSU", code: "20033", name: "Parathyroid Hormone + Ionized Calcium", purpose: "Evaluates calcium regulation and parathyroid function.", species: "Dog / Cat", specimen: "Serum", amount: "1 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Freeze; ship on ice overnight to arrive frozen or chilled.", notes: "Avoid separator gel: it can falsely increase calcium. Heparinized plasma is an alternative; never EDTA/citrate for this test.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1496", available: true),
        .init(id: "MSU-20006", provider: "MSU", code: "20006", name: "Endogenous ACTH", purpose: "Helps differentiate adrenal disease after appropriate diagnostic workup.", species: "Dog / Cat", specimen: "EDTA plasma", amount: "1 mL", tube: "Lavender • EDTA collection → plain leakproof PLASTIC transfer tube", preparation: "msuACTH", handling: "Freeze immediately after separation; overnight shipment on ice, arriving frozen/chilled.", notes: "Use plastic: ACTH binds glass. Collect before corticosteroids when clinically appropriate. This is the dog/cat protocol.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1706", available: true),
        .init(id: "MSU-11600", provider: "MSU", code: "11600", name: "CBC with Differential", purpose: "Blood-cell counts, reticulocytes and smear review.", species: "Dog / Cat", specimen: "EDTA whole blood + slides", amount: "0.25 mL minimum + 2 direct smears", tube: "Lavender • EDTA; rigid slide carrier", preparation: "msuCBC", handling: "Whole blood on cold pack; slides in rigid holder outside chilled compartment.", notes: "Tube must also be at least half full. Do not centrifuge or freeze.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1760", available: true),
        .init(id: "MSU-11294", provider: "MSU", code: "11294", name: "Cytology — Slides Only", purpose: "Microscopic evaluation of aspirated tissue.", species: "Dog / Cat", specimen: "Unstained slides", amount: "Slide count not specified; confirm for submission", tube: "Rigid slide carrier • no blood vial", preparation: "msuSlides", handling: "Rigid slide carrier; no formalin or cold packs.", notes: "Unstained, unfixed slides; label each site and include history.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1777", available: true),
        .init(id: "MSU-20014", provider: "MSU", code: "20014", name: "OFA Canine Thyroid Profile", purpose: "Thyroid testing for OFA registry submission.", species: "Dog", specimen: "Serum", amount: "2 mL", tube: "Serum collection tube → plain leakproof transfer tube (no gel)", preparation: "msuSerum", handling: "Freeze before overnight shipment on ice; follow current OFA acceptance criteria.", notes: "Fasting required. No thyroid therapy in prior 3 months under OFA criteria; do not stop prescribed treatment without the veterinarian. Include current OFA form.", source: "https://vdl.msu.edu/Bin/Catalog.exe?Action=Print&ID=1629", available: true),
        .init(id: "MSU-20004", provider: "MSU", code: "20004", name: "PTHrP", purpose: "Calcium-related malignancy investigation.", species: "Dog / Cat", specimen: "Unavailable", amount: "Do not collect for this unavailable test", tube: "No collection instruction while unavailable", preparation: "unavailable", handling: "Do not ship for this test.", notes: "MSU lists this test as unavailable. Review the PTH + ionized calcium option (20033) with the veterinarian.", source: "https://cvm.msu.edu/vdl/news/2026/extended-unavailability-of-pthrp-and-malignancy-profile", available: false),
        .init(id: "MSU-20030", provider: "MSU", code: "20030", name: "Malignancy Profile", purpose: "Calcium-related malignancy investigation.", species: "Dog / Cat", specimen: "Unavailable", amount: "Do not collect for this unavailable test", tube: "No collection instruction while unavailable", preparation: "unavailable", handling: "Do not ship for this test.", notes: "MSU lists this test as unavailable. Review the PTH + ionized calcium option (20033) with the veterinarian.", source: "https://cvm.msu.edu/vdl/news/2026/extended-unavailability-of-pthrp-and-malignancy-profile", available: false)
    ]
}

